### PR TITLE
add travis support

### LINKED ISSUE #7: travis support

### PR DESCRIPTION
**Pull request by robertkowalski**
fixes #7

### CODE REVIEW

**Comment by misterdjules** [comment]
LGTM, did you test it on Travis?

**Comment by robertkowalski** [comment]
I can't as I can't push it to master on my GH account as I transferred the repo from my account to TJ and a redirect is in place :(

**Comment by robertkowalski** [comment]
I'll try anyway, maybe it works.

**Comment by robertkowalski** [comment]
cool, it worked and is green: https://travis-ci.org/robertkowalski/node-documentation-generator

:)

**Comment by misterdjules** [comment]
@robertkowalski Great! Thanks for the update :)

**Pull request merged**
